### PR TITLE
Grammar fixes

### PR DESCRIPTION
**Pull request by amaanq**
Hi - foam is one of the dozen or so grammars that suffer from issues such as memory leaks, infinite loop hangs (case for this one), segfaults, etc. In an attempt to fix that - I reworked the logic to not use a copied haskell scanner and instead directly and simply run the logic. It works well and fuzzing reports nothing bad. I also tweaked identifier and boolean as they seemed somewhat wrong and updated the queries accordingly.

Thanks,
Amaan

### CODE REVIEW

**Comment by FoamScience** [comment]
Hi, Looks solid to me; I have actually started a similar effort but got distracted by other stuff!
I did my best to review in 30mins, nothing really comes off as risky so I'm willing to go with this as is.

I vaguely remember that I did booleans with "string literals" for a reason (probably LSP-related); but cannot remember why 😭 
Anyway, we're rolling with it for now
Thanks for the nice contribution

**Comment by FoamScience** [comment]
Also, a million thanks for adding a License 👍🏻. I have forgotten to do so a few times

**Comment by amaanq** [comment]
Thanks for merging! Though I forgot to update the windows tests as well, do you mind me PRing just changing that as well :sweat_smile:

**Comment by FoamScience** [comment]
Already done, no need :)

**Pull request merged**
